name: flutter_basics
description: HW 3.6
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.4
  carousel_slider:
    git:
      url: https://github.com/serenader2014/flutter_carousel_slider
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/notepad.svg